export const SOCKET_EVENTS = {
  // Client -> Server
  JOIN_ROOM: 'join_room',
  CREATE_ROOM: 'create_room',
  LEAVE_ROOM: 'leave_room',
  PLAY: 'play',
  PAUSE: 'pause',
  SEEK: 'seek',
  CHANGE_VIDEO: 'change_video',
  ASSIGN_ROLE: 'assign_role',
  REMOVE_PARTICIPANT: 'remove_participant',
  TRANSFER_HOST: 'transfer_host',
  REQUEST_CONTROL: 'request_control',
  REQUEST_PLAYBACK_CHANGE: 'request_playback_change',
  HANDLE_CONTROL_REQUEST: 'handle_control_request',
  APPROVE_REQUEST: 'approve_request',
  REJECT_REQUEST: 'reject_request',
  SEND_CHAT: 'send_chat',
  SEND_REACTION: 'send_reaction',
  SYNC_PING: 'sync_ping',
  DELETE_MESSAGE: 'delete_message',
  PIN_MESSAGE: 'pin_message',
  TIMEOUT_USER: 'timeout_user',
  UPDATE_QUEUE: 'update_queue',
  TOGGLE_SLOW_MODE: 'toggle_slow_mode',

  // Server -> Client
  SYNC_STATE: 'sync_state',
  ROOM_SNAPSHOT: 'room_snapshot',
  PARTICIPANTS_UPDATED: 'participants_updated',
  PRESENCE_UPDATED: 'presence_updated',
  USER_JOINED: 'user_joined',
  USER_LEFT: 'user_left',
  ROLE_ASSIGNED: 'role_assigned',
  PARTICIPANT_REMOVED: 'participant_removed',
  HOST_TRANSFERRED: 'host_transferred',
  CONTROL_REQUEST_SUBMITTED: 'control_request_submitted',
  CONTROL_REQUEST_UPDATED: 'control_request_updated',
  CHAT_MESSAGE: 'chat_message',
  MESSAGE_DELETED: 'message_deleted',
  MESSAGE_PINNED: 'message_pinned',
  USER_TIMED_OUT: 'user_timed_out',
  QUEUE_UPDATED: 'queue_updated',
  SLOW_MODE_UPDATED: 'slow_mode_updated',
  REACTION_RECEIVED: 'reaction_received',
  SYNC_PONG: 'sync_pong',
  ERROR_MESSAGE: 'error_message',
  ROOM_ERROR: 'room_error',
  ROOM_CLOSED: 'room_closed',
} as const;
